<<<<<<< HEAD
#' Show a single palette
#' 
#' Display a single palette to see whether it meets your needs.
#' If no \code{num} parameter is given,
#' all the colours in the palette will be displayed.
#' If \code{num} is less than the number of colours in the palette,
#' then only the first \code{num} colours will be displayed.
#' If \code{num} is greater than the number of colours in the palette,
#' then that many colours will be generated by linear interpolation
#' over the vector of colours in the chosen palette.
#' @param pal character, vector of (hexadecimal) colours representing a palette
#' @param ttl character, title to be displayed (the name of the palette)
#' @param num numeric, the number of colours to display
#' @examples
#' viz_palette(ochre_palettes$namatjira_qual)
#' viz_palette(ochre_palettes$namatjira_qual, "namatjira_qual")
#' viz_palette(ochre_palettes$namatjira_qual, "namatjira_qual first 4", 4)
#' viz_palette(ochre_palettes$namatjira_qual, "namatjira_qual interpolated to 25", 25)
#' 
#' @export
#' @importFrom graphics image
#' @importFrom grDevices colorRampPalette
#' 
viz_palette <- function(pal, ttl = "", num = length(pal)) {
=======
#' Show an ochre palette
#'
#' @param obj character, vector of (hexadecimal) colors characterizing a palette
#' @param name character, the name of the palette
#' @param num numeric, the number of colors to use
#' @export
#' @importFrom graphics image
#' @importFrom grDevices colorRampPalette
viz_palette <- function(obj, name = NULL, num = length(obj)) {
>>>>>>> c437cc2260556a426203fea40e2aa9bc8ad63cd3
    if(num <= 0)
        stop("'num' should be > 0")
    pal_func <- colorRampPalette(pal)
    image(seq_len(num), 1, as.matrix(seq_len(num)), col = pal_func(num), 
<<<<<<< HEAD
          main = paste0(ttl, " (", length(pal), " colours in palette, ", num, " displayed)"), 
          xlab = "", ylab = "", xaxt = "n", yaxt = "n",  bty = "n")
=======
          main = name, ylab = "", xaxt = "n", yaxt = "n",  bty = "n",
          xlab = "")
>>>>>>> c437cc2260556a426203fea40e2aa9bc8ad63cd3
}
